start
	= expression

char
	= [0-9a-zA-Z_?!+=@#$%^&*/.<>-]

spacechar
	= [ \t\r\n]*

space
	= spacechar ";;" [^\n]* !.
	/ spacechar (";;" [^\n]* "\n" spacechar)*

atom
	= space sign:[+-]? int:[0-9]+ dec:("." [0-9]+)? space
		{ return parseFloat(sign + int.join("") + (dec && "." + dec[1].join("")), 10); }
	/ space v:char+ space
		{ return v.join(""); }

expression
	= space "'" v:expression space
		{ return ["quote", v]; }
	/ atom
	/ space "(" v:expression* ")" space
		{ return v; }